# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/src

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: |
            TARGET_BRANCH=master
            changed_files=$(git diff --name-only remotes/origin/$TARGET_BRANCH..$CIRCLE_BRANCH)

            # If common, models, or other files are affected, run full tests
            common_models_files=$(echo $changed_files | tr ' ' '\n' | grep -oE "^src\/services\/(common|models)/" || true)
            common_models_affected=$(echo $common_models_files | awk "{print length}")
            others_files=$(echo $changed_files | tr ' ' '\n' | grep -v "^src\/services\/" || true)
            others_affected=$(echo $others_files | awk "{print length}")
            service_files=$(echo $changed_files | tr ' ' '\n' | grep -oE "^src\/services\/(.*)/" || true)
            services_affected=$(echo $service_files | awk "{print length}")

            if [ ${#services_affected} -gt 1 ] && [ ${#common_models_affected} -eq 1 ] && [ ${#others_affected} -eq 1 ]; then
                npm test -- $service_files
            else
                npm test
            fi